name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: "1"

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@main
    with:
      pre-commit-source: pre-commit

  verify-apps:
    name: Build apps
    needs: pre-commit
#    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
    uses: rmartin16/.github-beeware/.github/workflows/app-build-verify.yml@create-new-project
    with:
      runner-os: ${{ matrix.runner-os }}
      framework: ${{ matrix.framework }}
      target-platform: web
      target-format: static
    strategy:
      matrix:
        runner-os: [ "macos-latest", "windows-latest", "ubuntu-latest" ]
        framework: ["toga"]
