name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

env:
  python_version: "3.9"

defaults:
  run:
    shell: bash # https://github.com/beeware/briefcase/pull/912

jobs:
  verify-apps:
    name: Build apps
    strategy:
      matrix:
        os_name: ["macOS", "windows", "linux"]
        framework: ["toga"]
        include:
          - os_name: macOS
            platform: macos-12
            briefcase-data-dir: ~/Library/Caches/org.beeware.briefcase
            pip-cache-dir: ~/Library/Caches/pip
            docker-cache-dir: ~/Library/Containers/com.docker.docker/Data/vms/0/
          - os_name: windows
            platform: windows-latest
            briefcase-data-dir: ~\AppData\Local\BeeWare\briefcase\Cache
            pip-cache-dir: ~\AppData\Local\pip\Cache
            docker-cache-dir: C:\ProgramData\DockerDesktop
          - os_name: linux
            # Need to use at least 22.04 to get the bugfix in flatpak for handling spaces in filenames.
            platform: ubuntu-22.04
            briefcase-data-dir: ~/.cache/briefcase
            pip-cache-dir: ~/.cache/pip
            # cache action cannot cache docker images (actions/cache#31)
            # docker-cache-dir: /var/lib/docker
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Cache Briefcase tools
        uses: actions/cache@v3.0.11
        with:
          key: briefcase-${{ matrix.platform }}
          path: |
            ~/.cookiecutters
            ${{ matrix.briefcase-data-dir }}
            ${{ matrix.pip-cache-dir }}
            ${{ matrix.docker-cache-dir }}
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ env.python_version }}
      - name: Install system dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get install -y flatpak flatpak-builder
      - name: Install packages
        run: pip install briefcase
      - name: Build Web App
        run: |
          cd tests/apps/verify-${{ matrix.framework }}
          briefcase create web
          briefcase build web
          briefcase package web
